spring.application.name=slikskoven

#hibernate skriver ikke alle sql-forespørgsler i konsollen
#true: brugbart lokalt ved fejlsøgning
#false: mere ryddelige logs. Bruges ved produktion f.eks
spring.jpa.show-sql=false

# Første admin oprettes fra environment variables.
# De rigtige værdier må ikke stå i denne fil eller på GitHub.
app.admin.email=${ADMIN_EMAIL:}
app.admin.password=${ADMIN_PASSWORD:}
app.admin.name=${ADMIN_NAME}