spring.application.name=slikskoven

#hibernate skriver ikke alle sql-forespørgsler i konsollen
#true: brugbart lokalt ved fejlsøgning
#false: mere ryddelige logs. Bruges ved produktion f.eks
spring.jpa.show-sql=false
